# Generated by Django 2.2.4 on 2019-08-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190811_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
