# Generated by Django 2.2.4 on 2019-08-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190815_0221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
